### ISSUE TITLE
Quark Tomes cannot be Combined in an anvil

### ISSUE THREAD

**Issue by Elourge** [Forecaster/RailcraftPatronServer#4]
For example a Power 5 Tome and a Power 5 Enchanted Book should be able to combine into a Power 6 Enchanted Book for 35 levels as suggested in the wiki page 
http://quark.vazkii.us/#misc-ancient-tomes

However the result is that the combination is too expensive, even for Railcraft's steel anvil which boast a higher level cap.

**Comment by Elourge** [comment]
Further investigation shows that the config has been adjusted so that the cost to combine the books has been increased to Lvl50, therefore this issue lies with the Railcraft Anvil not being able to combine them

**Comment by Forecaster** [comment]
I have no idea how powerful that is and if it should be permitted, but the options are either to leave it be, re-configure Quark(?) to allow it, or that @CovertJaguar increases the cap of the steel anvil further.

Or, perhaps someone should make a mod that adds a diamond anvil if one does not already exist.

**Comment by Forecaster** [comment]
#7 This may help

**Comment by Generalcamo** [comment]
This is intentional. These are supposed to be the most powerful forms of the enchantment.

**Comment by CovertJaguar** [comment]
@Generalcamo intentional that you cannot use them at all? Seems kind of stupid way to achieve that. Are you the one who set them at 50?

**Comment by Generalcamo** [comment]
I thought this issue was only for combining books?

**Comment by Forecaster** [comment]
May need @Elourge to clarify if the issue is just combining the tome into a lvl 6 book, or using them otherwise

**Comment by Elourge** [comment]
I tested setting the level to combine books to 39 and it works, so the problem lies with railcraft anvil not actually increasing the cap it seems. any thing above that doesnt work

**Comment by CovertJaguar** [comment]
Eh?

**Comment by hanakocz** [comment]
Their only usage is to combine them with book to get that better book, they cannot be used directly at all.

**Comment by CovertJaguar** [comment]
From what I can tell, the Tome could charge 1 million levels and still work fine.

The only issue I see is that the GUI renders a different string if the cost is over the "expected max", but this has zero input on whether it actually works or not.

The event that Quark hooks, directly replaces all code dealing with max costs. So if quark doesn't care about cost, then the Anvil won't either.

**Comment by CovertJaguar** [comment]
Testing confirms the previous analysis. There is no issue here.
