### ISSUE TITLE
Iron boots with old scrapping ench cannot have enchantments added to it

### ISSUE THREAD

**Issue by liach** [Forecaster/RailcraftPatronServer#8]
FYI Scrapping was removed.

**Comment by liach** [comment]
Well that iron boots is masterful, I don't know how can I get another masterful one... It's rare!

**Comment by CovertJaguar** [comment]
I don't know what you want me to do about it... edit the NBT tag?

**Comment by liach** [comment]
Guess you should just delete the enchant tag, things will be fine

**Comment by CovertJaguar** [comment]
Are you wearing it? Ping me sometime with it in your inventory and I'll fix it.
